[project]
name = "lunance"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.1",
    "fastapi>=0.115.12",
    "passlib>=1.7.4",
    "pydantic[email]>=2.11.5",
    "pydantic-settings>=2.9.1",
    "pymysql>=1.1.1",
    "python-dotenv>=1.1.0",
    "python-jose>=3.5.0",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.34.3",
    "cryptography>=45.0.4",
    "python-multipart>=0.0.20",
    "bcrypt>=4.3.0",
    "google-genai>=1.22.0",
    "email-validator>=2.2.0",
    "pre-commit>=4.2.0",
    "slowapi>=0.1.9",
    "pillow>=12.0.0",
    "apscheduler>=3.11.2",
    "pytz>=2025.2",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.14.3",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "httpx>=0.28.1",
    "pytest-cov>=7.0.0",
    "pre-commit>=4.3.0",
]

[tool.ruff]
exclude = ["src/tests", "alembic/", "src/run_tests.py"]
