[package]
name = "fincore"
version = "0.1.1"
edition = "2021"

[lib]
name = "fincore"
crate-type = ["cdylib"]  # Genera una librería dinámica compatible con Python

[dependencies]
pyo3 = { version = "0.29.0", features = ["extension-module"] }
rust_decimal = { version = "1.40.0", features = ["maths"] }
