"""add_base_principal_to_investment_card_settings

Revision ID: 070c7148a41c
Revises: 2a5eafe3730f
Create Date: 2026-02-25 22:05:17.640219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070c7148a41c'
down_revision: Union[str, None] = '2a5eafe3730f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_card_settings', sa.Column('base_principal', sa.DECIMAL(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_card_settings', 'base_principal')
    # ### end Alembic commands ###
