"""Add password field

Revision ID: 16bd0ec21121
Revises: 8589ed21ca22
Create Date: 2026-03-18 11:37:15.059180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '16bd0ec21121'
down_revision: Union[str, None] = '8589ed21ca22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=True))
    op.alter_column('users', 'auth0_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth0_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
