"""add_investment_yield_repository_and_add_interest_type

Revision ID: 2a5eafe3730f
Revises: a11337a8a9cf
Create Date: 2026-02-24 20:25:38.319095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a5eafe3730f'
down_revision: Union[str, None] = 'a11337a8a9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_yields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('uuid', mysql.CHAR(length=36), nullable=False),
    sa.Column('yield_date', sa.Date(), nullable=False),
    sa.Column('principal_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('yield_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('cumulative_balance', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('annual_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('interest_type', sa.Enum('SIMPLE', 'COMPOUND', name='interesttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'yield_date', name='uq_account__yield_date')
    )
    op.create_index('idx_yield_date', 'investment_yields', ['yield_date'], unique=False)
    op.create_index(op.f('ix_investment_yields_account_id'), 'investment_yields', ['account_id'], unique=False)
    op.create_index(op.f('ix_investment_yields_uuid'), 'investment_yields', ['uuid'], unique=True)
    op.add_column('investment_card_settings', sa.Column('interest_type', sa.Enum('SIMPLE', 'COMPOUND', name='interesttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_card_settings', 'interest_type')
    op.drop_index(op.f('ix_investment_yields_uuid'), table_name='investment_yields')
    op.drop_index(op.f('ix_investment_yields_account_id'), table_name='investment_yields')
    op.drop_index('idx_yield_date', table_name='investment_yields')
    op.drop_table('investment_yields')
    # ### end Alembic commands ###
