"""Allow delete on cascade transactions when account is delete

Revision ID: 2aa46647ba1c
Revises: 3819628a97bb
Create Date: 2025-06-29 23:11:16.673441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa46647ba1c'
down_revision: Union[str, None] = '3819628a97bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_ibfk_1'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['account_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_ibfk_1'), 'transactions', 'accounts', ['account_id'], ['account_id'])
    # ### end Alembic commands ###
