"""fix typo in refresh_tokens table

Revision ID: 3819628a97bb
Revises: e0f310a9a09d
Create Date: 2025-06-24 20:46:50.041058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3819628a97bb'
down_revision: Union[str, None] = 'e0f310a9a09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('refresh_tokens', 'id_revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('id_revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('refresh_tokens', 'is_revoked')
    # ### end Alembic commands ###
