"""add recurring incomes and income deposits tables

Revision ID: 387f87a035cc
Revises: 2349ed266dfa
Create Date: 2026-07-15 22:37:52.219431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387f87a035cc'
down_revision: Union[str, None] = '2349ed266dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_incomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'BIMONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', name='frequency'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_payment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_incomes_id'), 'recurring_incomes', ['id'], unique=False)
    op.create_index(op.f('ix_recurring_incomes_is_active'), 'recurring_incomes', ['is_active'], unique=False)
    op.create_index(op.f('ix_recurring_incomes_next_payment_date'), 'recurring_incomes', ['next_payment_date'], unique=False)
    op.create_index(op.f('ix_recurring_incomes_start_date'), 'recurring_incomes', ['start_date'], unique=False)
    op.create_index(op.f('ix_recurring_incomes_user_id'), 'recurring_incomes', ['user_id'], unique=False)
    op.create_index(op.f('ix_recurring_incomes_uuid'), 'recurring_incomes', ['uuid'], unique=True)
    op.create_table('income_deposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recurring_income_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'PAGADO', 'FALLIDO', 'CANCELADO', name='transactionstatus'), nullable=False),
    sa.Column('processing_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recurring_income_id'], ['recurring_incomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurring_income_id', 'deposit_date', name='uq_income_deposit_date')
    )
    op.create_index(op.f('ix_income_deposits_deposit_date'), 'income_deposits', ['deposit_date'], unique=False)
    op.create_index(op.f('ix_income_deposits_id'), 'income_deposits', ['id'], unique=False)
    op.create_index(op.f('ix_income_deposits_recurring_income_id'), 'income_deposits', ['recurring_income_id'], unique=False)
    op.create_index(op.f('ix_income_deposits_status'), 'income_deposits', ['status'], unique=False)
    op.create_index(op.f('ix_income_deposits_uuid'), 'income_deposits', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_deposits_uuid'), table_name='income_deposits')
    op.drop_index(op.f('ix_income_deposits_status'), table_name='income_deposits')
    op.drop_index(op.f('ix_income_deposits_recurring_income_id'), table_name='income_deposits')
    op.drop_index(op.f('ix_income_deposits_id'), table_name='income_deposits')
    op.drop_index(op.f('ix_income_deposits_deposit_date'), table_name='income_deposits')
    op.drop_table('income_deposits')
    op.drop_index(op.f('ix_recurring_incomes_uuid'), table_name='recurring_incomes')
    op.drop_index(op.f('ix_recurring_incomes_user_id'), table_name='recurring_incomes')
    op.drop_index(op.f('ix_recurring_incomes_start_date'), table_name='recurring_incomes')
    op.drop_index(op.f('ix_recurring_incomes_next_payment_date'), table_name='recurring_incomes')
    op.drop_index(op.f('ix_recurring_incomes_is_active'), table_name='recurring_incomes')
    op.drop_index(op.f('ix_recurring_incomes_id'), table_name='recurring_incomes')
    op.drop_table('recurring_incomes')
    # ### end Alembic commands ###
