"""remove password_hash and add auth0 id

Revision ID: 576461220653
Revises: 68ed0c4f8143
Create Date: 2025-11-14 01:11:49.924170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '576461220653'
down_revision: Union[str, None] = '68ed0c4f8143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('picture', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'picture')
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###
