"""Add account_id and UUID for saving goals table

Revision ID: 602f90c4e93c
Revises: 70b33b266175
Create Date: 2026-05-27 23:24:17.028666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '602f90c4e93c'
down_revision: Union[str, None] = '70b33b266175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_goals', sa.Column('uuid', sa.CHAR(length=36), nullable=False))
    op.alter_column('saving_goals', 'account_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_saving_goals_uuid'), 'saving_goals', ['uuid'], unique=True)
    op.drop_column('saving_goals', 'current_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_goals', sa.Column('current_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False))
    op.drop_index(op.f('ix_saving_goals_uuid'), table_name='saving_goals')
    op.alter_column('saving_goals', 'account_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('saving_goals', 'uuid')
    # ### end Alembic commands ###
