"""feat: add uuid to budgets table

Revision ID: 70b33b266175
Revises: a506e34efada
Create Date: 2026-05-25 18:21:32.947104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b33b266175'
down_revision: Union[str, None] = 'a506e34efada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('uuid', sa.CHAR(length=36), nullable=False))
    op.create_index(op.f('ix_budgets_uuid'), 'budgets', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_uuid'), table_name='budgets')
    op.drop_column('budgets', 'uuid')
    # ### end Alembic commands ###
