"""add uuid to subscription_charges

Revision ID: 7f089b5dc7e3
Revises: 576461220653
Create Date: 2026-01-22 14:21:13.428529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f089b5dc7e3'
down_revision: Union[str, None] = '576461220653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_charges', sa.Column('uuid', sa.CHAR(length=36), nullable=False))
    op.create_index(op.f('ix_subscription_charges_uuid'), 'subscription_charges', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_charges_uuid'), table_name='subscription_charges')
    op.drop_column('subscription_charges', 'uuid')
    # ### end Alembic commands ###
