"""Add credit_card_settings and investment_card_settings tables

Revision ID: 809e09ff210b
Revises: 7f089b5dc7e3
Create Date: 2026-02-02 19:00:01.455252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '809e09ff210b'
down_revision: Union[str, None] = '7f089b5dc7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('uuid', mysql.CHAR(length=36), nullable=False),
    sa.Column('billing_cycle_day', sa.Integer(), nullable=False),
    sa.Column('payment_due_day', sa.Integer(), nullable=False),
    sa.Column('credit_limit', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('minimum_payment_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_billing_cycle_day', 'credit_card_settings', ['billing_cycle_day'], unique=False)
    op.create_index('idx_payment_due_day', 'credit_card_settings', ['payment_due_day'], unique=False)
    op.create_index(op.f('ix_credit_card_settings_account_id'), 'credit_card_settings', ['account_id'], unique=True)
    op.create_index(op.f('ix_credit_card_settings_uuid'), 'credit_card_settings', ['uuid'], unique=True)
    op.create_table('investment_card_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('uuid', mysql.CHAR(length=36), nullable=False),
    sa.Column('investment_type', sa.String(length=50), nullable=False),
    sa.Column('investment_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('lock_period_end_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('early_withdrawal_penalty', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lock_period_end_date', 'investment_card_settings', ['lock_period_end_date'], unique=False)
    op.create_index('idx_maturity_date', 'investment_card_settings', ['maturity_date'], unique=False)
    op.create_index(op.f('ix_investment_card_settings_account_id'), 'investment_card_settings', ['account_id'], unique=True)
    op.create_index(op.f('ix_investment_card_settings_uuid'), 'investment_card_settings', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_card_settings_uuid'), table_name='investment_card_settings')
    op.drop_index(op.f('ix_investment_card_settings_account_id'), table_name='investment_card_settings')
    op.drop_index('idx_maturity_date', table_name='investment_card_settings')
    op.drop_index('idx_lock_period_end_date', table_name='investment_card_settings')
    op.drop_table('investment_card_settings')
    op.drop_index(op.f('ix_credit_card_settings_uuid'), table_name='credit_card_settings')
    op.drop_index(op.f('ix_credit_card_settings_account_id'), table_name='credit_card_settings')
    op.drop_index('idx_payment_due_day', table_name='credit_card_settings')
    op.drop_index('idx_billing_cycle_day', table_name='credit_card_settings')
    op.drop_table('credit_card_settings')
    # ### end Alembic commands ###
