"""Bank id on accounts is mandatory

Revision ID: 8589ed21ca22
Revises: b3f92a1d4e07
Create Date: 2026-03-08 22:39:48.530104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8589ed21ca22'
down_revision: Union[str, None] = 'b3f92a1d4e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_ibfk_2'), 'accounts', type_='foreignkey')
    op.alter_column('accounts', 'bank_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'accounts', 'banks', ['bank_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('accounts_ibfk_2'), 'accounts', 'banks', ['bank_id'], ['id'], ondelete='SET NULL')
    op.alter_column('accounts', 'bank_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
