"""add unique constraint uq_subscription_charge_date to subscription_charges

Revision ID: 9b63f73d3bb5
Revises: 387f87a035cc
Create Date: 2026-07-22 21:55:08.455996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b63f73d3bb5'
down_revision: Union[str, None] = '387f87a035cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subscription_charge_date', 'subscription_charges', ['subscription_id', 'charge_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subscription_charge_date', 'subscription_charges', type_='unique')
    # ### end Alembic commands ###
