"""Fix timezone in notifications table

Revision ID: 9f6a64c1ac3f
Revises: c14f0b558d46
Create Date: 2026-04-24 20:17:58.637372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6a64c1ac3f'
down_revision: Union[str, None] = 'c14f0b558d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    # ### end Alembic commands ###
