"""add_bank_table

Revision ID: a11337a8a9cf
Revises: aa4dc41329c1
Create Date: 2026-02-04 12:02:55.959956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a11337a8a9cf'
down_revision: Union[str, None] = 'aa4dc41329c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_code'), 'banks', ['code'], unique=True)
    op.create_index(op.f('ix_banks_id'), 'banks', ['id'], unique=False)
    op.add_column('accounts', sa.Column('bank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'banks', ['bank_id'], ['id'], ondelete='SET NULL')
    op.drop_column('accounts', 'bank')
    op.drop_constraint(op.f('fk_subscription_charges_transaction_id'), 'subscription_charges', type_='foreignkey')
    op.create_foreign_key(None, 'subscription_charges', 'transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_charges', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscription_charges_transaction_id'), 'subscription_charges', 'transactions', ['transaction_id'], ['id'], ondelete='CASCADE')
    op.add_column('accounts', sa.Column('bank', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'bank_id')
    op.drop_index(op.f('ix_banks_id'), table_name='banks')
    op.drop_index(op.f('ix_banks_code'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
