"""add installment purchases and charges tables

Revision ID: a506e34efada
Revises: 9f6a64c1ac3f
Create Date: 2026-05-16 00:36:16.814651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a506e34efada'
down_revision: Union[str, None] = '9f6a64c1ac3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installment_purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('num_installments', sa.Integer(), nullable=False),
    sa.Column('installment_type', sa.Enum('NO_INTEREST', 'WITH_INTEREST', name='installmenttype'), nullable=False),
    sa.Column('annual_interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('monthly_payment', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_purchases_user_id'), 'installment_purchases', ['user_id'], unique=False)
    op.create_index(op.f('ix_installment_purchases_uuid'), 'installment_purchases', ['uuid'], unique=True)
    op.create_table('installment_charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('installment_purchase_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installment_purchase_id'], ['installment_purchases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installment_charges_due_date'), 'installment_charges', ['due_date'], unique=False)
    op.create_index(op.f('ix_installment_charges_installment_purchase_id'), 'installment_charges', ['installment_purchase_id'], unique=False)
    op.create_index(op.f('ix_installment_charges_uuid'), 'installment_charges', ['uuid'], unique=True)
    op.alter_column('subscriptions', 'frequency',
               existing_type=mysql.ENUM('DIARIA', 'SEMANAL', 'QUINCENAL', 'MENSUAL', 'BIMENSUAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL'),
               type_=sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'BIMONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', name='frequency'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'frequency',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'BIMONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', name='frequency'),
               type_=mysql.ENUM('DIARIA', 'SEMANAL', 'QUINCENAL', 'MENSUAL', 'BIMENSUAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL'),
               existing_nullable=False)
    op.drop_index(op.f('ix_installment_charges_uuid'), table_name='installment_charges')
    op.drop_index(op.f('ix_installment_charges_installment_purchase_id'), table_name='installment_charges')
    op.drop_index(op.f('ix_installment_charges_due_date'), table_name='installment_charges')
    op.drop_table('installment_charges')
    op.drop_index(op.f('ix_installment_purchases_uuid'), table_name='installment_purchases')
    op.drop_index(op.f('ix_installment_purchases_user_id'), table_name='installment_purchases')
    op.drop_table('installment_purchases')
    # ### end Alembic commands ###
