"""add next_charge_date to subscriptions

Revision ID: b808e02b7a51
Revises: 9b63f73d3bb5
Create Date: 2026-07-23 22:46:24.851063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b808e02b7a51'
down_revision: Union[str, None] = '9b63f73d3bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('next_charge_date', sa.Date(), nullable=False))
    op.create_index(op.f('ix_subscriptions_next_charge_date'), 'subscriptions', ['next_charge_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_next_charge_date'), table_name='subscriptions')
    op.drop_column('subscriptions', 'next_charge_date')
    # ### end Alembic commands ###
