"""Add table to notifications

Revision ID: c14f0b558d46
Revises: 4c07f822b8ca
Create Date: 2026-04-24 18:53:53.713984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c14f0b558d46'
down_revision: Union[str, None] = '4c07f822b8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('SMS', 'EMAIL', 'PUSH', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('accounts', 'current_balance',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False)
    op.alter_column('accounts', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.alter_column('accounts', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('accounts', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('budgets', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('budgets', 'alert_percentage',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('budgets', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('categories', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('investment_card_settings', 'lock_period_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('reminders', 'type',
               existing_type=mysql.ENUM('PAGO', 'COBRO', 'REVISION', 'OTRO'),
               nullable=False)
    op.alter_column('reminders', 'is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('reminders', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('saving_goals', 'current_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False)
    op.alter_column('saving_goals', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('saving_goals', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('subscription_charges', 'status',
               existing_type=mysql.ENUM('PENDIENTE', 'PAGADO', 'FALLIDO', 'CANCELADO'),
               nullable=False)
    op.alter_column('subscriptions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('subscriptions', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('transactions', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'uuid',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    op.alter_column('users', 'email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'registration_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registration_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'uuid',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    op.alter_column('transactions', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('subscriptions', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('subscriptions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('subscription_charges', 'status',
               existing_type=mysql.ENUM('PENDIENTE', 'PAGADO', 'FALLIDO', 'CANCELADO'),
               nullable=True)
    op.alter_column('saving_goals', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('saving_goals', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('saving_goals', 'current_amount',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True)
    op.alter_column('reminders', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('reminders', 'is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('reminders', 'type',
               existing_type=mysql.ENUM('PAGO', 'COBRO', 'REVISION', 'OTRO'),
               nullable=True)
    op.alter_column('refresh_tokens', 'is_revoked',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('investment_card_settings', 'lock_period_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('categories', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('budgets', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('budgets', 'alert_percentage',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('budgets', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('accounts', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('accounts', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('accounts', 'currency',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('accounts', 'current_balance',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
