"""add transfer_uuid to transactions

Revision ID: f02b8a82c09d
Revises: 602f90c4e93c
Create Date: 2026-05-30 01:04:24.879935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02b8a82c09d'
down_revision: Union[str, None] = '602f90c4e93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transfer_uuid', sa.CHAR(length=36), nullable=True))
    op.create_index(op.f('ix_transactions_transfer_uuid'), 'transactions', ['transfer_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transfer_uuid'), table_name='transactions')
    op.drop_column('transactions', 'transfer_uuid')
    # ### end Alembic commands ###
