from dataclasses import dataclass
from datetime import datetime, date, timezone
from typing import Optional

from domain.objects.frequency import first_occurrence, next_occurrence
from domain.objects.money import Money
from domain.objects.enums import Frequency
from shared.exceptions.domain import InvalidSubscriptionDateRangeError


@dataclass
class Subscription:
    id: Optional[int]
    uuid: Optional[str]
    user_id: int
    account_id: int
    category_id: int
    name: str
    amount: Money
    frequency: Frequency
    start_date: date
    end_date: Optional[date]
    billing_day: Optional[int]
    is_active: bool
    description: Optional[str]
    service_url: Optional[str]
    next_charge_date: date
    creation_date: Optional[datetime] = None

    @classmethod
    def create_new(
        cls,
        user_id: int,
        account_id: int,
        category_id: int,
        name: str,
        amount: Money,
        frequency: Frequency,
        start_date: date,
        end_date: Optional[date],
        billing_day: Optional[int],
        description: Optional[str],
        service_url: Optional[str],
        next_charge_date: Optional[date] = None,
    ):
        if end_date is not None and end_date < start_date:
            raise InvalidSubscriptionDateRangeError(str(start_date), str(end_date))

        if next_charge_date is None:
            next_charge_date = first_occurrence(start_date, frequency, billing_day)

        return cls(
            id=None,
            uuid=None,  # This will be generated by the repository
            user_id=user_id,
            account_id=account_id,
            category_id=category_id,
            name=name,
            amount=amount,
            frequency=frequency,
            start_date=start_date,
            end_date=end_date,
            billing_day=billing_day,
            next_charge_date=next_charge_date,
            is_active=True,
            description=description,
            service_url=service_url,
            creation_date=datetime.now(timezone.utc),
        )

    def anchor_day(self) -> int:
        return self.billing_day if self.billing_day is not None else self.start_date.day

    def is_due(self, as_of: date) -> bool:
        if not self.is_active:
            return False
        if self.end_date and self.next_charge_date > self.end_date:
            return False
        return self.next_charge_date <= as_of

    def advance_next_charge(self) -> None:
        self.next_charge_date = next_occurrence(
            self.next_charge_date, self.frequency, self.anchor_day()
        )

    def reschedule(self, as_of: date) -> None:
        """Recalcula la agenda tras cambiar frequency / start_date / billing_day."""
        base = max(self.start_date, as_of)
        self.next_charge_date = first_occurrence(base, self.frequency, self.billing_day)
