from dataclasses import dataclass
from datetime import datetime, date
from typing import Optional

from domain.objects.money import Money
from domain.objects.enums import Frequency


@dataclass
class Subscription:
    id: Optional[int]
    uuid: Optional[str]
    user_id: int
    account_id: int
    category_id: int
    name: str
    amount: Money
    frequency: Frequency
    start_date: date
    end_date: Optional[date]
    billing_day: Optional[int]
    is_active: bool
    description: Optional[str]
    service_url: Optional[str]
    creation_date: Optional[datetime] = None

    @classmethod
    def create_new(
        cls,
        user_id: int,
        account_id: int,
        category_id: int,
        name: str,
        amount: Money,
        frequency: Frequency,
        start_date: date,
        end_date: Optional[date],
        billing_day: Optional[int],
        description: Optional[str],
        service_url: Optional[str],
    ):
        return cls(
            id=None,
            uuid=None,  # This will be generated by the repository
            user_id=user_id,
            account_id=account_id,
            category_id=category_id,
            name=name,
            amount=amount,
            frequency=frequency,
            start_date=start_date,
            end_date=end_date,
            billing_day=billing_day,
            is_active=True,
            description=description,
            service_url=service_url,
            creation_date=datetime.now(),
        )
